hmcts/fpla-docker

- README.md
- compose/frontend.yml
N/A
Expose the `PROXY_PAYMENTS` variable for stubbing
```
[ ] Yes
[x] No
```
> impr: expose proxy payments variable

- bin/add-roles.sh
- bin/users.json
Added adoption clerk role and user.
```
[ ] Yes
[x] No
```
> feat: added adoption clerk user (FPLA-1226)

- bin/add-services.sh
Updated redirect url & password for adoption service in idam
> Updating redirect url for adoption frontend in idam

- README.md
> impr: Small improvements to README

- compose/xui.yml
- mocks/wiremock/mappings/payments/cases/ccdCaseNumber-paymentGroups.json
Fix payment URL and mock 
```
[ ] Yes
[X] No
```
> fix: payment mocks configuration

- compose/frontend.yml
[FPLA-1892](https://tools.hmcts.net/jira/browse/FPLA-1892)
Added ccd shutter redirect url and wait time
```
[ ] Yes
[x] No
```
> feat: define shutter variables

- mocks/wiremock/mappings/organisations.json
**Before creating a pull request make sure that:**
https://tools.hmcts.net/jira/browse/FPLA-1921
Updated organisation.json wiremock data
```
[ ] Yes
[x] No
```
> feat: updated organisation api wiremock data (FPLA-1921)

- bin/users.json
adding new users with distinct roles
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Update users.json (FPLA-840)

- bin/users.json
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> fix: user.json formatting

- README.md
- compose/frontend.yml
https://tools.hmcts.net/jira/browse/FPLA-1772
Remove references to CCD UI from FPL when live
```
[ ] Yes
[* ] No
```
> feat: remove references to CCD UI from FPL when live (FPLA-1772)

- bin/add-roles.sh
- bin/users.json
**Before creating a pull request make sure that:**
Added user to support FPL shared storage
```
[ ] Yes
[x] No
```
> Added user to support shared storage

- bin/utils/fpl-process-definition.sh
> Docker mounted dir for docker jenkins agents

- bin/add-roles.sh
- bin/users.json
https://tools.hmcts.net/jira/browse/FPLA-1872
Add super user
```
[ ] Yes
[ *] No
```
> feat: add super user role (FPLA-1872)

- bin/users.json
> fix: Update email to mailnesia

- bin/utils/fpl-process-definition.sh
- mocks/wiremock/mappings/fee-register/c2-without-notice.json
Jenkins docker agent compatibility updates. 
```
[ ] Yes
[ ] No
```
> Jenkins agents volumes compatibility

- mocks/wiremock/templates/userByEmail.json
http://rd-professional-api-demo.service.core-compute-demo.internal/swagger-ui.html
https://tools.hmcts.net/jira/browse/FPLA-2034
> feat: pass user email via header when searching for an user in reference data (FPLA-2034)

- bin/utils/fpl-process-definition.sh
> Update ccd definition processor version to support searchable field

- bin/utils/ccd-add-role.sh
- bin/utils/idam-add-role.sh
- bin/utils/idam-authenticate.sh
- bin/utils/idam-create-caseworker.sh
- bin/utils/idam-create-service.sh
- bin/utils/idam-lease-service-token.sh
- bin/utils/idam-lease-user-token.sh
- bin/utils/idam-update-service.sh
> Revert "chore: Retry curl requests that ends with http 5xx"

- compose/backend.yml
see
https://github.com/hmcts/ccd-data-store-api/blob/81b3e620c2bd93350f07a2afe6b935d548c46973/src/main/resources/application.properties#L77
> chore: whitelist fpl to allow access to new assignment endpoint

- compose/backend.yml
- compose/frontend.yml
- compose/sidam.yml
- ccd wiremock
- ccd web admin
- idam mail server
- idam web admin
> chore: Disable optional services

- mocks/wiremock/__files/prd/allOrganisations.json
- mocks/wiremock/mappings/allOrganisations.json
http://rd-professional-api-aat.service.core-compute-aat.internal/swagger-ui.html#/organisation-external-controller/retrieveOrganisationsByStatusWithAddressDetailsOptionalUsingGET
> feat: mock prd endpoint that gets list of all orgs

- compose/sidam.yml
- mocks/wiremock/__files/payments/case/payments.json
- mocks/wiremock/mappings/payments/cases/ccdCaseNumber-payments.json
https://tools.hmcts.net/jira/browse/FPLA-2910
> feat: add case payments mock (FPLA-2910)

- ccd
We need images from the hmctspublic repo as well.
```
[ ] Yes
[X] No
```
> fix: adding log-in to public hmcts image repo to ccd script

- bin/utils/ccd-import-definition.sh
> Use shuttered case def when env flag set

- bin/utils/ccd-import-definition.sh
Fix bash command substitution for the shuttering check
```
[ ] Yes
[X] No
```
> Fix command substitution

- compose/elasticsearch.yml
Updating local docker env elastic search to version 7
```
[ ] Yes
[ x] No
```
> Updating elastic search to version 7

- bin/utils/ccd-import-definition.sh
https://tools.hmcts.net/jira/browse/DFPL-1455
Extra logging for error 404 investigation
```
[ ] Yes
[X] No
```
> add debug messages for 404 error investigation

- bin/utils/idam-lease-service-token.sh
https://tools.hmcts.net/jira/browse/DFPL-1455
Remove `testing-support` in  `idam-lease-service-token.sh`
```
[ ] Yes
[X No
```
> remove testing-support

- bin/utils/fpl-process-definition.sh
https://tools.hmcts.net/jira/browse/DFPL-1463
- Use latest def processor version (needed for SearchCriteria)
```
[ ] Yes
[X] No
```
> Use latest def processor version
